language: python
python:
  - "3.6" 

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests 
# This is the script that enables travis to run the tests
# There are many ways to do dependeing on how you want travis to run and get you coverage
script: true
  - nosetests --with-coverage --coverage report

# command to run tests
script:
  - pytest

# This returns the coverage and let's coveralls know the coverage percent. 
# Note that travis will build your system and get the coverage. 
# It cannot display, therefore coveralls becomes important to get the coverage
# You can also use after_success
# Find out more about after_script and after_success 
after_script:
  - coveralls
 
# Using codecov to get coverage
after_success:
  - codecov
